language: cpp
compiler:
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/tools/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - mkdir build && cd build
  - python ../configure.py --enable-optimize --sdks=episode1,tf2,l4d2,csgo,dota
  - ambuild